### ISSUE TITLE
ComputerCraft turtles crash server

### ISSUE THREAD

**Issue by Gerkinfeltser** [Towsty/iLabsRedux#13]
Refueling, moving via scripting, etc. turtles cause server to crash.
![2016-01-05 12_08_03-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/1477787/12121781/21e09884-b3a5-11e5-8d14-8b48524b96f6.png)

**Comment by Towsty** [comment]
Fixed in R2 1.1
