### ISSUE TITLE
redux2: Bloodstone

### ISSUE THREAD

**Issue by hollowhalls** [Towsty/iLabsRedux#3]
to make a bloodstone with out a bloodmoon present you toss a fully charged whitestone into a teir 2 blood alter with 5k lp

**Comment by Towsty** [comment]
Fully charged whitestone in a Tier 3 (felt a little more right to me :P) altar, 5k LP = Uncharged Bloodstone

![image](https://cloud.githubusercontent.com/assets/5897643/11321743/449541b4-9090-11e5-9373-6da4f8325584.png)
